import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { openStore, validate } from '../store.mjs';
import { publicEntries } from '../curated.mjs';
const good={title:'Test film',creator:'Maker',email:'maker@example.com',description:'A test',video:'https://youtu.be/dQw4w9WgXcQ',product:'',category:'Experiment',tools:'HyperFrames',permission:true,hyperframes:true};
test('validates supported links and rejects unsafe inputs',()=>{assert.equal(validate(good).title,'Test film');for(const changes of [{video:'javascript:alert(1)'},{product:'http://example.com'},{email:'nope'},{permission:false},{hyperframes:false},{title:'a'.repeat(101)},{video:'https://example.com/not-video'}])assert.throws(()=>validate({...good,...changes}));});
test('pending entries stay private; approval persists on reopening',()=>{const dir=mkdtempSync(join(tmpdir(),'showcase-test-'));let db;try{db=openStore(dir);db.prepare('INSERT INTO entries (id,title,creator,email,description,video,category,tools) VALUES (?,?,?,?,?,?,?,?)').run('test','Title','Maker','private@example.com','Description',good.video,'Experiment','HyperFrames');assert.deepEqual(publicEntries(db).map(e=>e.id),['website-to-video','poultry-path']);db.prepare("UPDATE entries SET status='approved' WHERE id='test'").run();db.close();db=openStore(dir);assert.deepEqual(publicEntries(db).map(e=>e.id),['website-to-video','poultry-path','test']);assert.ok(publicEntries(db).every(e=>!('email' in e)));}finally{db?.close();rmSync(dir,{recursive:true,force:true});}});
test('older database row does not duplicate the published project',()=>{const dir=mkdtempSync(join(tmpdir(),'showcase-test-'));const db=openStore(dir);try{db.prepare('INSERT INTO entries (id,title,creator,email,description,video,category,tools,status) VALUES (?,?,?,?,?,?,?,?,?)').run('poultry-path','Poultry Path','Gowtham','','Old entry',good.video,'Product demo','HyperFrames','approved');assert.deepEqual(publicEntries(db).map(e=>e.id),['website-to-video','poultry-path']);}finally{db.close();rmSync(dir,{recursive:true,force:true});}});
